  UPDATE SYS_POSTING_DATE
  SET POSTING_DATE = (SELECT CURRENT_CYCLE_END FROM CBR_BILLING_CYCLE WHERE INSTITUTION_NUMBER = '00000108')
  WHERE INSTITUTION_NUMBER = '00000108'
  AND STATION_NUMBER = '129';
  commit;