/*
This SQL script's objective is insert random acquirer batch inputs. Save time because dont need to login into WebGui.
Input params:
- 1: institution_number
- 2: client_number (one to many, seperated by comma)
- 3: delete merchant? Y: Yes / empty: NO      

Output: update/delete data in:
- HST_STATEMENT_ACCOUNT
- HST_STATEMENT_ADDRESS
- HST_STATEMENT_HISTORY
- HST_STATEMENT_ACCT_BALANCE
- HST_STATEMENT_MESSAGES
- HST_STATEMENT_LOG
- HST_STATEMENT_TRANSACTIONS  
- INT_ADDENDUM_XXXX (GENERIC_DETAIL, _GL_CONTRA, _AIRLINE_ANCILLARY,..)
- INT_ADDENDUM_INFORMATION   
- INT_ADDENDUM_GL_CONTRA 
- INT_ADDENDUM_ADDITIONAL_DATA   
- INT_FILE_LOG_DETAILS   
- int_gl_transactions 
- INT_SUNDRY_HISTORY    
- INT_SUNDRY_TRANSACTIONS 
- INT_TRANSACTION_AMENDMENT     
- int_transactions    
- INT_ADDENDUM_CHARGES
- INT_BATCH_CAPTURE
- CAS_ACCOUNT_XXX (_CHANGE_HISTORY , _CYCLE_CHANGEM _STATUS_CHANGEM, _TRANSFER_LOG)  
- CAS_CYCLE_BOOK_BALANCE     

Use cases: BA, Testers, Automation test.
Developed and maintained by: HUNG.HO@RS2.COM
*/

-- CREATE OR REPLACE PROCEDURE RESET_MERCHANT_BALANCE (V_INSTITUTION_NUMBER IN VARCHAR, v_client_number IN VARCHAR, v_audit_trail IN VARCHAR)
-- IS
-- BEGIN

SET DEFINE ON;
SET SERVEROUTPUT ON;

DECLARE
	-- MANUAL PARAMS
	V_INSTITUTION_NUMBER VARCHAR2(8) := '&1';
	v_client_number VARCHAR2(100) := '&2'; -- 81
    v_delete_merchant varchar2(1) := '&3'; -- Y: Yes / empty: NO   
    
    v_audit_trail VARCHAR2(16) := 'MANUAL_INPUT_';
	-- FIXED PARAMS
	v_posting_date VARCHAR2(8);
	v_system_date VARCHAR2(8);

BEGIN     
	SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') INTO v_system_date FROM DUAL; -- get system date
	v_audit_trail := v_audit_trail || v_system_date;
	
	FOR curClientNumber in (WITH DATA AS ( SELECT v_client_number str FROM dual) SELECT trim(COLUMN_VALUE) str FROM DATA, xmltable(('"' || REPLACE(REPLACE(REPLACE(str, ' ', ''), ',', '","'), '|', '","') || '"'))) LOOP
  		v_client_number := trim(curClientNumber.str);

	    DELETE FROM HST_STATEMENT_ACCOUNT 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;  --
		DELETE FROM HST_STATEMENT_ADDRESS 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;
		DELETE FROM HST_STATEMENT_HISTORY 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;
		DELETE FROM HST_STATEMENT_ADDRESS 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM HST_STATEMENT_ACCT_BALANCE 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM HST_STATEMENT_MESSAGES WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM HST_STATEMENT_LOG WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER);
		DELETE FROM HST_STATEMENT_TRANSACTIONS 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';

		DELETE FROM INT_ADDENDUM_GENERIC_DETAIL WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and transaction_slip in (
	    	select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

	    DELETE FROM INT_ADDENDUM_GL_CONTRA 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
	    	and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_AIRLINE  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			  and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_AIRLINE_ANCILLARY  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_AIRLINE_LEGS  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_AUTO_RENTAL  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_BADD  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_ECOMMERCE  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_CUP  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_FLEET_SERVICE  where    INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_GENERIC_DETAIL  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_GL_CONTRA  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_HOTEL_LODGING  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_INFORMATION  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_LINE_ITEM  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_MAIL_PHONE_ORDER  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_PAYMENT  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

	  	DELETE FROM INT_ADDENDUM_PAYMENT_SERVICE  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

	    DELETE FROM INT_ADDENDUM_PETROLEUM  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ADDENDUM_REFERENCE_DATA  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_ORIG_MESSAGE  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in (select transaction_slip from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

		DELETE FROM INT_FILE_LOG_DETAILS  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in (select file_number from int_transactions where  CLIENT_NUMBER = V_CLIENT_NUMBER and  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER);

	    DELETE FROM INT_ADDENDUM_GL_CONTRA where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and GL_TRANSACTION_SLIP in (
			select transaction_slip from int_gl_transactions  where    INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions
			where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER));

		DELETE FROM int_gl_transactions  where INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER);

		DELETE FROM INT_SUNDRY_HISTORY  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER    ;
		DELETE FROM INT_SUNDRY_TRANSACTIONS  where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER    ;

		DELETE FROM INT_ADDENDUM_ADDITIONAL_DATA   where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in ( select transaction_slip  from int_transactions where       INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions
			where   INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER )
			and transaction_class = '002' and TRANSACTION_CATEGORY = '001'
			) ;

		DELETE FROM INT_ADDENDUM_CHARGES   where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and transaction_slip in  ( select transaction_slip  from int_transactions where       INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions
			where     INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER)
			and transaction_class = '002' and TRANSACTION_CATEGORY = '001'
			) ;

		DELETE FROM int_transactions where  INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
			and file_number in ( select distinct file_number from int_transactions where    INSTITUTION_NUMBER = V_INSTITUTION_NUMBER and CLIENT_NUMBER = V_CLIENT_NUMBER );

		DELETE FROM INT_ADDENDUM_CHARGES WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;
		DELETE FROM INT_BATCH_CAPTURE 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;


	  	DELETE FROM INT_TRANSACTION_AMENDMENT WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;  --
	  	DELETE FROM INT_MERCHANT_TIER_STATISTICS WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND CLIENT_NUMBER = V_CLIENT_NUMBER;  --

	  	DELETE FROM CAS_ACCOUNT_CHANGE_HISTORY 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM CAS_ACCOUNT_CYCLE_CHANGE 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM CAS_ACCOUNT_STATUS_CHANGE 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';
		DELETE FROM CAS_ACCOUNT_TRANSFER_LOG 	WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER AND SRC_ACCT_NUMBER LIKE V_CLIENT_NUMBER || '%';

		-- DBMS_OUTPUT.put_line('UDDATE CAS_CYCLE_BOOK_BALANCE ACCT_NUMBER=' || REC.ACCT_NUMBER || ' CURRENT_CYCLE_START=' || REC.CURRENT_CYCLE_START || ' ACCT_CURRENCY=' || REC.ACCT_CURRENCY);
		UPDATE CAS_CYCLE_BOOK_BALANCE
		SET
		  	BEGIN_BALANCE = '0',
			CURRENT_BALANCE = '0',
			DR_BALANCE_CASH = '0',
			DR_BALANCE_RETAIL = '0',
			DR_BALANCE_INTEREST = '0',
			DR_BALANCE_CHARGES = '0',
			CR_BALANCE_PAYMENTS = '0',
			CR_BALANCE_REFUNDS = '0',
			CR_BALANCE_INTEREST = '0',
			CR_BALANCE_BONUS = '0',
			AMOUNT_HIGH_BAL_DR = '0',
			AMOUNT_LOW_BAL_DR = '0',
			AMOUNT_HIGH_BAL_CR = '0',
			AMOUNT_LOW_BAL_CR = '0',
			NUMBER_TRAN_CHRG_DR = '0',
			NUMBER_TRAN_CHRG_CR = '0',
			NUMBER_TRAN_NONCHRG_DR = '0',
			NUMBER_TRAN_NONCHRG_CR = '0',
			TRAN_CHARGES = '0',
			PENDING_AUTHS = '0',
			AUDIT_TRAIL  = v_audit_trail,
			LOCKING_COUNTER = '0',
			CURRENT_BALANCE_CASH = '0',
			INSTALLMENT_BALANCE = '0',
			LAST_BALANCE_UPDATE = v_system_date
	 		WHERE
	 			INSTITUTION_NUMBER = V_INSTITUTION_NUMBER
	 			AND ACCT_NUMBER LIKE V_CLIENT_NUMBER||'%'
	 			AND PROCESSING_STATUS = '004';

          	DBMS_OUTPUT.put_line('COMPLETED RESET MERCHANT DATA: ' || v_client_number);
	END LOOP; -- Client number
	COMMIT;

exception
	WHEN NO_DATA_FOUND THEN
		null;
	when others then
		dbms_output.put_line('An error occurred '|| chr(10) || sqlerrm || chr(10) || dbms_utility.format_error_backtrace);rollback;
END;
-- END;
/

