SELECT * FROM CIS_CLIENT_DETAILS 				WHERE INSTITUTION_NUMBER = :institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM SVC_CLIENT_SERVICE 				WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_DEVICE_LINK 					WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_CLIENT_TAX_STATUS 			WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_SETTLEMENT_INFORMATION 		WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_CLIENT_LINKS 					WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_ADDRESSES 					WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CIS_CLIENT_ADDENDUM				WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;

SELECT * FROM CAS_CYCLE_BOOK_BALANCE 			WHERE INSTITUTION_NUMBER = &institution_number AND ACCT_NUMBER LIKE (&client_number || '%');
SELECT * FROM CAS_CLIENT_ACCOUNT 				WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM CAS_ACCT_INSTRUCTIONS 			WHERE INSTITUTION_NUMBER = &institution_number AND ACCT_NUMBER LIKE &client_number||'%';
SELECT * FROM CAS_CLIENT_FEES					WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;

SELECT * FROM HST_STATEMENT_ACCOUNT 			WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;  --
SELECT * FROM HST_STATEMENT_ADDRESS 			WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM HST_STATEMENT_HISTORY 			WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM INT_ADDENDUM_CHARGES 				WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM INT_BATCH_CAPTURE 				WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;
SELECT * FROM INT_TRANSACTIONS 					WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;  --
SELECT * FROM INT_TRANSACTION_AMENDMENT 		WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;  --
SELECT * FROM INT_MERCHANT_TIER_STATISTICS 		WHERE INSTITUTION_NUMBER = &institution_number AND CLIENT_NUMBER = &client_number;  --
SELECT * FROM CAS_ACCOUNT_CHANGE_HISTORY 		WHERE INSTITUTION_NUMBER = &institution_number AND ACCT_NUMBER LIKE &client_number||'%';
SELECT * FROM CAS_ACCOUNT_CYCLE_CHANGE 			WHERE INSTITUTION_NUMBER = &institution_number AND ACCT_NUMBER LIKE &client_number||'%';
SELECT * FROM CAS_ACCOUNT_STATUS_CHANGE 		WHERE INSTITUTION_NUMBER = &institution_number AND ACCT_NUMBER LIKE &client_number||'%';
SELECT * FROM CAS_ACCOUNT_TRANSFER_LOG 			WHERE INSTITUTION_NUMBER = &institution_number AND SRC_ACCT_NUMBER LIKE &client_number||'%';