procedure BW_UPDATE_ADD_NUMBER IS

 CURSOR ADD_LINE IS
    SELECT * FROM INT_ADDENDUM_LINE_ITEM
    WHERE LENGTH(ITEM_SEQ_NO) > 4;

NO_OF_CHARS			VARCHAR2(3);
ADD_VAL				VARCHAR2(15);


BEGIN

-----------------------
-- INT_ADDENDUM_LINE_ITEM
-----------------------

BEGIN
  SELECT CHAR_LENGTH INTO NO_OF_CHARS FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'INT_ADDENDUM_LINE_ITEM'
  AND TRIM(COLUMN_NAME) = 'ITEM_SEQ_NO';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NO_OF_CHARS := 0;
END;

IF NO_OF_CHARS > 4 THEN

	FOR ADD_REC IN ADD_LINE

	  LOOP

      ADD_VAL := SUBSTR(TRIM(ADD_REC.ITEM_SEQ_NO),  -4);

      UPDATE INT_ADDENDUM_LINE_ITEM
        SET ITEM_SEQ_NO = ADD_VAL
        WHERE INSTITUTION_NUMBER = ADD_REC.INSTITUTION_NUMBER
        AND ITEM_SEQ_NO = ADD_REC.ITEM_SEQ_NO
        AND TRANSACTION_SLIP = ADD_REC.TRANSACTION_SLIP;

    END LOOP;

    EXECUTE IMMEDIATE 'ALTER TABLE INT_ADDENDUM_LINE_ITEM
        MODIFY ITEM_SEQ_NO VARCHAR2(4)';

END IF;

COMMIT;

END;