FUNCTION GET_TOTAL_PENDING_AUTH_CASH (VIN_INSTNUMBER IN CAS_ONLINE_ACCOUNT.INSTITUTION_NUMBER%TYPE,
                                                       VIN_LIMITNUMBER IN CAS_ONLINE_ACCOUNT.LIMIT_NUMBER%TYPE,
                                                       VIN_CLIENTNUMBER IN CAS_ONLINE_ACCOUNT.CLIENT_NUMBER%TYPE,
                                                       VIN_ACCTCURRENCY IN CAS_ONLINE_ACCOUNT.ACCT_CURRENCY%TYPE )
RETURN VARCHAR2 IS

V_RETURN VARCHAR2(50);

STRACCTNUMBER VARCHAR2(11);

CURSOR CUR_ACCTSHARED IS SELECT ACCT_NUMBER FROM CAS_CLIENT_ACCOUNT
                 WHERE INSTITUTION_NUMBER = VIN_INSTNUMBER
                AND LIMIT_NUMBER = VIN_LIMITNUMBER
                AND ACCOUNT_LEVEL = '001'
                AND ACCT_CURRENCY = VIN_ACCTCURRENCY;

CURSOR CUR_ACCTALLOCATED IS SELECT ACCT_NUMBER FROM CAS_CLIENT_ACCOUNT
              WHERE CLIENT_NUMBER = VIN_CLIENTNUMBER
              AND INSTITUTION_NUMBER = VIN_INSTNUMBER
              AND LIMIT_NUMBER = VIN_LIMITNUMBER;

BEGIN
 OPEN CUR_ACCTSHARED;
 FETCH CUR_ACCTSHARED INTO STRACCTNUMBER;
 V_RETURN := '';
 IF CUR_ACCTSHARED%FOUND THEN
   SELECT NVL(LTRIM(TO_CHAR(SUM(TO_NUMBER(NVL(ACCOUNT_AMOUNT_NET,'0'))))),0) INTO V_RETURN
   FROM INT_ONLINE_TRANSACTIONS
   WHERE INSTITUTION_NUMBER = VIN_INSTNUMBER
   AND TRANSACTION_CLASS = '010'
   AND TRANSACTION_STATUS = '005'
   AND TRANSACTION_TYPE IN ('007','009')
    AND ACCT_NUMBER IN (SELECT ACCT_NUMBER FROM CAS_CLIENT_ACCOUNT
					   WHERE INSTITUTION_NUMBER = VIN_INSTNUMBER
	 				   AND LIMIT_NUMBER = VIN_LIMITNUMBER);
 ELSE
  OPEN CUR_ACCTALLOCATED;
  FETCH CUR_ACCTALLOCATED INTO STRACCTNUMBER;
  IF CUR_ACCTALLOCATED%FOUND THEN
     SELECT NVL(LTRIM(TO_CHAR(SUM(TO_NUMBER(NVL(ACCOUNT_AMOUNT_NET,'0'))))),0) INTO V_RETURN
     FROM INT_ONLINE_TRANSACTIONS
     WHERE INSTITUTION_NUMBER = VIN_INSTNUMBER
     AND TRANSACTION_CLASS = '010'
     AND TRANSACTION_STATUS = '005'
     AND TRANSACTION_TYPE IN ('007','009')
      AND ACCT_NUMBER IN (SELECT ACCT_NUMBER FROM CAS_CLIENT_ACCOUNT
                WHERE INSTITUTION_NUMBER = VIN_INSTNUMBER
                START WITH INSTITUTION_NUMBER = VIN_INSTNUMBER
                    AND ACCT_NUMBER = STRACCTNUMBER
                CONNECT BY PRIOR ACCT_NUMBER = PARENT_ACCOUNT_NUMBER
                     AND PRIOR INSTITUTION_NUMBER = VIN_INSTNUMBER);
  END IF;
  CLOSE CUR_ACCTALLOCATED;
 END IF;
 CLOSE CUR_ACCTSHARED;
 RETURN V_RETURN;
END;