FUNCTION "GET_MRCSTMT_SUMMARY" (VIEWNAME_IN IN VARCHAR2, INSTNO_IN IN VARCHAR2, CLIENTNO_IN IN VARCHAR2, DATESTMT_IN IN VARCHAR2)
                            RETURN VARCHAR2
IS
    V_RETURN VARCHAR2(18);
    V_SQL_STMT VARCHAR2(200);
BEGIN
    IF VIEWNAME_IN = 'VIEW_MERCH_STMT_DEP_ORG_SUMM' THEN
    	SELECT SUM(ACCOUNT_AMOUNT_NET) INTO V_RETURN
		FROM VIEW_MERCH_STMT_DEP_ORG_SUMM
		WHERE INSTITUTION_NUMBER = INSTNO_IN
		AND CLIENT_NUMBER = CLIENTNO_IN
		AND STATEMENT_SECTION = 'DPST_Summ'
		AND DATE_STATEMENT_END = DATESTMT_IN;
	ELSIF VIEWNAME_IN = 'VIEW_MERCH_STMT_FUND_SUMM' THEN
		SELECT SUM(DEPOSIT_AMT+CHARGEBACK_AMT+ADJUSTMENT_AMT+CHARGES_FEES_AMT) INTO V_RETURN
		FROM VIEW_MERCH_STMT_FUND_SUMM
		WHERE INSTITUTION_NUMBER = INSTNO_IN
		AND CLIENT_NUMBER = CLIENTNO_IN
		AND DATE_STATEMENT_END = DATESTMT_IN;
	ELSE
		V_SQL_STMT := 'SELECT SUM(ACCOUNT_AMOUNT_NET) AS AMT
						FROM '	|| VIEWNAME_IN ||
						' WHERE INSTITUTION_NUMBER = :1
						AND CLIENT_NUMBER = :2
						AND DATE_STATEMENT_END = :3' ;
		EXECUTE IMMEDIATE V_SQL_STMT INTO V_RETURN USING INSTNO_IN, CLIENTNO_IN, DATESTMT_IN;
	END IF;

    RETURN V_RETURN;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END GET_MRCSTMT_SUMMARY;