FUNCTION "GET_DATA" (COLUMN_NAME IN VARCHAR2, TABLE_NAME IN VARCHAR2, INST_NO IN VARCHAR2, INDEX_FIELD IN VARCHAR2) RETURN VARCHAR2
IS
    V_QUERY VARCHAR2(1000);
    V_VALUE VARCHAR2(30);

BEGIN
    V_QUERY := 'select ' || COLUMN_NAME || ' from ' || TABLE_NAME || ' where institution_number = ' || INST_NO || ' AND ' || ' index_field = ' || INDEX_FIELD   ;

    EXECUTE IMMEDIATE V_QUERY
    INTO  V_VALUE;

    RETURN V_VALUE;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END GET_DATA;