SET PAGESIZE 1000000

SET FEEDBACK OFF

SET MARKUP HTML ON

SET WORD_WRAPPED ON

SET NUM 32

SET HEADING ON

spool /CI_Pipeline/Profiles/BNZ_DEV_INST_108_MIKE/qa_training/Builds/&1/SentFolder/myexcel.xls

SELECT
'MC001' AS TEST_CASE_ID,
'With master card 010' AS DESCRIPTION,
'N' AS SMS,
MERCHANT_COUNTRY AS MER_COUNTRY,
TERMINAL_ID AS TERMINAL_ID,
MERCHANT_NUMBER AS MERCHANT_ID,
'3005' AS MCC,
'Argentina' AS BIN_COUNTRY,
'MCG' AS PRODUCT_ID,
'MCC' AS  SUB_PRODUCT,
'Credit Card' AS CARD_SERVICE,
'N' AS PAYPASS,
'SALE' AS TRAN_TYPE,
TRAN_CURRENCY AS TRAN_CURR,
TRAN_AMOUNT_NET AS TRAN_AMOUNT,
'' AS INSTALLMENT_TYPE,
'0' AS INSTALLMENT_COUNT,
'0' AS "FIRST_INSTALLMENT_AMOUNT",
'5' AS TIMELINESS,
'' AS SETT_CURR,
'' AS SETT_AMOUNT,
'' AS CASHBACK,
'' AS TC,
'' AS CM,
'2' AS "DE22.01",
'1' AS "DE22.02",
'0' AS "DE22.03",
'1' AS "DE22.04",
'0' AS "DE22.05",
'1' AS "DE22.06",
'B' AS "DE22.07",
'5' AS "DE22.08",
'4' AS "DE22.09",
'0' AS "DE22.10",
'4' AS "DE22.11",
'6' AS "DE22.12",
'POI' AS PDS0023,
'220' AS ECOMM_DATA,
'00' AS AUTH_RESPONSE,
'Y' AS AUTH,
'0' AS UCAF_IND,
'' AS WALLET_ID,
'' AS CARD_NUMBER,
'' AS AUTH_IND,
'' AS SPEND_IND,
'' AS MARKET_DATA,
'' AS BAI,
'' AS MGIS_VGIS,
'N' AS AIRLINE_ADDENDUM,
'N' AS PAYFAC_ADDENDUM,
'' AS FEE_RULE,
'' AS FEE_RATE,
'' AS FEE_IDENTIFIER,
'' AS FEE_BASE,
'' AS FEE_MINIMUM,
'' AS FEE_MAXIMUM,
'' AS cvv2,
'' AS trans_time,
'' AS trace_id
FROM INT_TRANSACTIONS
where rownum <= 10;

SPOOL OFF

SET MARKUP HTML OFF

SPOOL OFF