SET DEFINE ON;
SET SERVEROUTPUT ON;

DECLARE
	-- MANUAL PARAMS
	V_INSTITUTION_NUMBER VARCHAR2(8) := '&1';

BEGIN   
	DELETE FROM HST_STATEMENT_ACCOUNT WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER  ;
	DELETE FROM HST_STATEMENT_ACCT_BALANCE WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER  ;
	DELETE FROM HST_STATEMENT_ADDRESS WHERE INSTITUTION_NUMBER = V_INSTITUTION_NUMBER  ;
	DELETE FROM INT_FILE_LOG_DETAILS WHERE PROCESS_NAME = '000145' AND institution_number = V_INSTITUTION_NUMBER;
	DELETE FROM HST_STATEMENT_LOG WHERE institution_number = V_INSTITUTION_NUMBER ;
	Update CAS_CLIENT_ACCOUNT SET last_statement_date='' WHERE institution_number = V_INSTITUTION_NUMBER AND last_statement_date <> '00000000' ;
	dbms_output.put_line('EXECUTE BEFORE PROCESS 145 SUCCESSFUL !');
	COMMIT;
END;
/
