  UPDATE SYS_POSTING_DATE
  SET POSTING_DATE = (SELECT CURRENT_CYCLE_START FROM CBR_BILLING_CYCLE WHERE INSTITUTION_NUMBER = '00000114')
  WHERE INSTITUTION_NUMBER = '00000114'
  AND POSTING_DATE < (SELECT CURRENT_CYCLE_START FROM CBR_BILLING_CYCLE WHERE INSTITUTION_NUMBER = '00000114')
  AND STATION_NUMBER = '129';
  commit;