REM BAK NONE

DECLARE
	v_application_number VARCHAR2(8);
	v_institution_number VARCHAR2(8) := '00000114';

BEGIN

    for rec in (
		SELECT 	APPLICATION_NUMBER
		INTO 	v_application_number
		FROM 	CIS_APPLICATION_DETAIL
		WHERE 	INSTITUTION_NUMBER = v_institution_number
		AND		CLIENT_NUMBER LIKE '988889%'
		AND 	ROWNUM = 1
	)
	loop
		---TODO PROPERLY
		DELETE FROM CIS_APPLICATION_DETAIL 		WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CIS_SETTLEMENT_INFORMATION 	WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CIS_CLIENT_LINKS 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CIS_ADDRESSES 				WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CIS_CLIENT_ADDENDUM 		WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CAS_CLIENT_ACCOUNT 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CAS_CLIENT_ACCOUNT 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CAS_ACCOUNT_CHANGE_HISTORY 	WHERE INSTITUTION_NUMBER = v_institution_number AND ACCT_NUMBER 		LIKE '988889%';
		DELETE FROM CIS_CLIENT_DETAILS 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER    	LIKE '988889%';
		DELETE FROM CIS_DEVICE_LINK 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER    	LIKE '988889%';
		DELETE FROM CAS_CYCLE_BOOK_BALANCE 		WHERE INSTITUTION_NUMBER = v_institution_number AND ACCT_NUMBER    		LIKE '988889%';
		DELETE FROM SVC_CLIENT_SERVICE 			WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CPS_PORTAL_USER_ACTIVATION  WHERE USERID IN (	SELECT 	USERID
																	FROM 	CPS_USER_INFORMATION
																	WHERE 	INSTITUTION_NUMBER = v_institution_number
																	AND 	CLIENT_NUMBER LIKE '988889%');
		DELETE FROM CPS_USER_INFORMATION		WHERE INSTITUTION_NUMBER = v_institution_number AND CLIENT_NUMBER      	LIKE '988889%';
		DELETE FROM CIS_APPLICATION_ADDR 		WHERE INSTITUTION_NUMBER = v_institution_number AND APPLICATION_NUMBER = v_application_number;
		DELETE FROM CIS_APPLICATION_ACCT_TYPE	WHERE INSTITUTION_NUMBER = v_institution_number AND APPLICATION_NUMBER = v_application_number;
		DELETE FROM CIS_APPLICATION_SERVICES 	WHERE INSTITUTION_NUMBER = v_institution_number AND APPLICATION_NUMBER = v_application_number;
		DELETE FROM CIS_APPL_CLIENT_ADDENDUM 	WHERE INSTITUTION_NUMBER = v_institution_number AND APPLICATION_NUMBER = v_application_number;
	end loop;

	COMMIT;

END;
/
