select * from CIS_SETTLEMENT_INFORMATION where INSTITUTION_NUMBER     = '00002001' and CLIENT_NUMBER   = '00000004'   order by 1;

---CIS_SETTLEMENT_INFORMATION.COUNTER_BANK_NUMBER= CIS_MANDATE_INFORMATION.RECORD_ID
---CIS_SETTLEMENT_INFORMATION.PAYMENT_REFERENCE = CIS_MANDATE_INFORMATION.UNIQUE_MANDATE_REF
---CIS_SETTLEMENT_INFORMATION.FUNDING_BANK = INSTITUTION_NUMBER if ENTITY_ID = 001 ( FSEU)
---CIS_SETTLEMENT_INFORMATION.FUNDING_BANK = 90000102 if   ENTITY_ID =  002 - Trust Payment (FSEU)  
-- CIS_MANDATE_INFORMATION: 2 fiels Instrument_code and first_occurrence must be 000, 000 


select * from CIS_CLIENT_LINKS      where INSTITUTION_NUMBER     = '00002001' and CLIENT_NUMBER   = '00000004'   order by 1;



select * from CIS_MANDATE_INFORMATION     where INSTITUTION_NUMBER     = '00002001'   order by 1;
