SELECT  DISTINCT CHT.INDEX_FIELD,
        CHT.POSTING_METHOD,
        (SELECT SWIFT_CODE FROM BW3.BWT_CURRENCY WHERE INSTITUTION_NUMBER = &1 AND ISO_CODE = CBR.ACCT_CURRENCY) AS ACCT_CURRENCY,
        LISTAGG((SELECT TRANSACTION_TYPE FROM CHT_TRANSACTION_TYPE WHERE INSTITUTION_NUMBER = &1 AND INDEX_FIELD = CBR.TRANSACTION_TYPE), ',') WITHIN GROUP (ORDER BY CBR.ACCT_CURRENCY, CBR.TRANSACTION_CATEGORY, CBR.TRANSACTION_CLASS, CBR.TRAN_CURRENCY, CBR.ACCOUNT_TYPE_ID) AS TRANSACTION_TYPE,
        (SELECT TYPE_ID FROM BW3.CHT_ACCOUNT_TYPE_ID WHERE INSTITUTION_NUMBER = &1 AND INDEX_FIELD = CBR.ACCOUNT_TYPE_ID) AS ACCOUNT_TYPE_ID,
        (SELECT TRANSACTION_CATEGORY FROM BW3.BWT_TRANSACTION_CATEGORY WHERE INSTITUTION_NUMBER = &1 AND INDEX_FIELD = CBR.TRANSACTION_CATEGORY) AS TRANSACTION_CATEGORY,
        (SELECT TRANSACTION_CLASS FROM BW3.BWT_TRANSACTION_CLASS WHERE INSTITUTION_NUMBER = &1 AND INDEX_FIELD = CBR.TRANSACTION_CLASS) AS TRANSACTION_CLASS,
        (CASE WHEN CBR.TRAN_CURRENCY = '999' THEN 'ALL' ELSE (SELECT SWIFT_CODE FROM BW3.BWT_CURRENCY WHERE INSTITUTION_NUMBER = &1 AND ISO_CODE = CBR.TRAN_CURRENCY) END) AS TRANSACTION_CURRENCY
FROM    CBR_POSTING_INSTRUCTIONS CBR,
        CHT_POSTING_TARIFF CHT
WHERE   CBR.INSTITUTION_NUMBER = &1
AND     CBR.INSTITUTION_NUMBER = CHT.INSTITUTION_NUMBER
AND     CBR.POSTING_METHOD = CHT.INDEX_FIELD
AND     CBR.SERVICE_CONTRACT_ID = '112'
GROUP BY CHT.INDEX_FIELD, CHT.POSTING_METHOD,CBR.TRANSACTION_CATEGORY, CBR.TRANSACTION_CLASS,CBR.ACCOUNT_TYPE_ID,CBR.TRAN_CURRENCY, CBR.ACCT_CURRENCY
ORDER BY 1,2,3,6,5,7;

select acct_number  from INT_TRANSACTIONS  where file_number = '00002506' and INSTITUTION_NUMBER  = '00000111'
and transaction_class = '012'
and  client_number = '00000181'
 order by transaction_class;

select service_contract_id from cas_client_account where INSTITUTION_NUMBER = '00000111' and acct_number = '00000181001';

select * from int_transactions where transaction_slip in (
select retrieval_reference from INT_TRANSACTIONS    where
file_number = 2587  --- pos nt loader
and INSTITUTION_NUMBER    = '00000111'
and transaction_class = '012')
and file_number = '00002661'
and    INSTITUTION_NUMBER    = '00000111'
and transaction_class = '002'
and client_number = '00000181'
;

